package com.raysdata.cep.store;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Component;

import com.raysdata.cep.model.User;

/**
 * Data access for user accounts.
 * <p>
 * Stores users in the <code>users</code> MongoDB collection. On first startup
 * (empty collection) a bootstrap admin account is created from configuration.
 */
@Component
public class UserStore {

    private static final Logger log = LoggerFactory.getLogger(UserStore.class);
    private static final String COLLECTION = "users";

    private final MongoTemplate mongoTemplate;
    private final BCryptPasswordEncoder passwordEncoder;
    private final String adminUsername;
    private final String adminPassword;
    private final String adminDisplayName;
    private final boolean passwordAutoGenerated;

    public UserStore(MongoTemplate mongoTemplate,
                     @Value("${cep.security.bootstrap-admin.username:admin}") String adminUsername,
                     @Value("${cep.security.bootstrap-admin.password:}") String adminPassword,
                     @Value("${cep.security.bootstrap-admin.display-name:Administrator}") String adminDisplayName) {
        this.mongoTemplate = mongoTemplate;
        this.passwordEncoder = new BCryptPasswordEncoder();
        this.adminUsername = adminUsername;
        // SEC-05: never fall back to a weak well-known password. If no strong
        // password is configured, generate a random one and surface it in the log.
        boolean weak = isWeakPassword(adminPassword);
        this.passwordAutoGenerated = weak;
        this.adminPassword = weak ? generateRandomPassword() : adminPassword;
        this.adminDisplayName = adminDisplayName;
        bootstrapAdmin();
    }

    private static boolean isWeakPassword(String p) {
        return p == null || p.isBlank() || "admin".equals(p) || p.length() < 8;
    }

    private String generateRandomPassword() {
        String chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789";
        java.security.SecureRandom rnd = new java.security.SecureRandom();
        StringBuilder sb = new StringBuilder(16);
        for (int i = 0; i < 16; i++) {
            sb.append(chars.charAt(rnd.nextInt(chars.length())));
        }
        return sb.toString();
    }

    public User findByUsername(String username) {
        return mongoTemplate.findOne(
                Query.query(Criteria.where("username").is(username)),
                User.class, COLLECTION);
    }

    public List<User> findAll() {
        return mongoTemplate.findAll(User.class, COLLECTION);
    }

    public boolean exists() {
        return mongoTemplate.count(new Query(), COLLECTION) > 0;
    }

    /**
     * Bootstrap a default admin account when the users collection is empty.
     * Runs once on startup.
     */
    private void bootstrapAdmin() {
        if (exists()) {
            return;
        }
        User admin = new User(adminUsername, passwordEncoder.encode(adminPassword),
                adminDisplayName, "admin");
        mongoTemplate.insert(admin, COLLECTION);
        if (passwordAutoGenerated) {
            log.warn("Created bootstrap admin account '{}'. No password was configured, "
                    + "so a random one was generated: {}  "
                    + "(set cep.security.bootstrap-admin.password / CEP_ADMIN_PASSWORD "
                    + "to control it explicitly).", adminUsername, adminPassword);
        } else {
            log.info("Created bootstrap admin account '{}'.", adminUsername);
        }
    }

    /**
     * Verify a plaintext password against the stored BCrypt hash.
     */
    public boolean matchesPassword(User user, String rawPassword) {
        if (user == null || user.getPasswordHash() == null) {
            return false;
        }
        return passwordEncoder.matches(rawPassword, user.getPasswordHash());
    }
}
